default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: uv-lock-check
        name: uv-lock-check
        entry: uv lock --check
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      - id: ruff
        name: ruff-lint
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes, -v ]

      - id: ruff-format
        args: [ -v ]
