system: >
  You are provided with a math problem and the groundtruth answer in english to that problem, your task is to translate the math problem into a given language and to generate a step by step solution to that problem that results in the provided answer.

  Note:
  - Provide the prompt JSON format, each with fields: "problem_translation", "step_by_step_response"
  - Your output should be in the provided language
  - Ensure that you Preserve the entity names that are mentioned in the original math problem
  - Ensure that you preserve numbers, mathematical formulas or symbols that are provided in the original prompt in the response
  - In the generated solution, wrap the final answer in a <answer></answer> tag

  Examples:



user: >
  Math Problem: {{prompt}}
  Answer: {{answer}}
  Language: {{language}}